assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite:
            apply_to: "\.css$"
        sass:
            apply_to: "\.sass$"
        coffee:
            apply_to: "\.coffee$"
        closure: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
